<?php

namespace Database\Seeders;

use App\Models\FormFormat;
use Illuminate\Database\Seeder;

/**
 * Catálogo del motor de formatos (Tier 4).
 *
 * Los formatos y sus ítems salen de las hojas de los dos libros que entregó
 * CMK: «Herramienta SG SST - PESV ONE DRIVE v1.xlsm» y «Herramienta SGI 2025
 * PARCONT SAS.xlsb». Las inspecciones se extrajeron de las hojas; las actas se
 * modelaron a mano porque un acta no es una lista de chequeo sino secciones
 * (objetivo, asistentes, agenda, desarrollo, compromisos).
 *
 * Varias hojas están DUPLICADAS entre los dos libros — extintores, EPP,
 * locativa, gerencial y la lista de chequeo de auditoría aparecen en ambos. Se
 * carga UNA sola vez, con los ítems de la versión más completa. Sembrar las dos
 * dejaría al consultor eligiendo entre dos formatos idénticos.
 *
 * Los preoperacionales de vehículo van UNO POR DÍA. En el Excel son una rejilla
 * de ítems × días del mes, pero eso es la consolidación mensual de la misma
 * inspección: aquí cada registro es un día, y su fecha vive en
 * `form_records.fecha`.
 *
 * Tipos de campo del esquema:
 *   text | textarea | date | number | select(opciones) | checklist(items) | firma
 *
 * CMK puede añadir más formatos desde la plataforma.
 */
class FormFormatsSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->formatos() as $f) {
            FormFormat::updateOrCreate(['codigo' => $f['codigo']], $f);
        }

        $this->command?->info('Formatos: '.count($this->formatos()).' cargados.');
    }

    private function formatos(): array
    {
        return [
            [
                'codigo'         => 'FT-INS-EXT',
                'nombre'         => 'Inspección de extintores',
                'categoria'      => 'SST',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Estado, carga y accesibilidad de cada extintor.',
                'orden'          => 10,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'MANOMETRO',
                                    'PASADOR DE SEGURIDAD',
                                    'MANGUERA',
                                    'BOQUILLA',
                                    'MANIJA',
                                    'CILINDRO',
                                    'PINTURA',
                                    'SEÑALIZACIÓN',
                                    'ACCESO',
                                    'VISIBILIDAD',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-EPP',
                'nombre'         => 'Inspección de uso y estado de EPP y dotación',
                'categoria'      => 'SST',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Uso y estado de la dotación y los elementos de protección personal entregados.',
                'orden'          => 20,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'BOTAS',
                                    'CAMISA/ PANTALÓN',
                                    'CASCO',
                                    'GUANTES',
                                    'PROT. AUDITIVA',
                                    'GAFAS',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-LOC',
                'nombre'         => 'Inspección locativa',
                'categoria'      => 'SST',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Condiciones locativas de las instalaciones: pisos, techos, escaleras, señalización.',
                'orden'          => 30,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'BUENO: B REGULAR: R MALO: M PROBABILIDAD: ALTA : A MEDIA : M BAJA: B',
                                    'PARAMETROS A CHEQUEAR',
                                    'INSTALACIONES',
                                    'Pisos -Techos',
                                    'Puertas y Ventanas',
                                    'Muebles',
                                    'Escaleras con Cinta antideslizante y Pasamanos',
                                    'Archivadores anclados o fijos a la pared y debidamente organizados',
                                    'Condiciones ambientales (ruido, temperatura o vibraciones)',
                                    'Los cables están en buen estado y no sueltos por el piso',
                                    'SISTEMA DE EMERGENCIA',
                                    'Planos de evacuación',
                                    'Salida de emergencia señalizada',
                                    'Rutas de evacuación señalizadas',
                                    'Sistema de comunicación en buen estado',
                                    'Teléfonos de emergencia publicados.',
                                    '¿Se ha realizado simulacro de evacuación en el ultimo año?',
                                    'Extintores recargados y señalizados',
                                    'SISTEMA ELECTRICO Y DE ILUMINACION',
                                    'Equipos eléctricos con polo a tierra',
                                    'Sistemas eléctricos en buen estado',
                                    'Tomas eléctricas sin sobrecargar',
                                    'Luminarias funcionando',
                                    'Limpieza de luminarias',
                                    'PRIMEROS AUXILIOS',
                                    'Botiquín de primeros auxilios dotado',
                                    'Elementos del botiquín vigentes',
                                    'ultima inspeccion de botiquin',
                                    'CONTROL DE RIESGOS',
                                    'Altura de puestos de trabajo ( debe estar entre 73 y 76 cms)',
                                    'Sillas',
                                    'Ventilación',
                                    'Iluminación',
                                    'Se realizan pausas activas',
                                    'ORDEN Y ASEO',
                                    'Áreas de trabajo limpias y en orden',
                                    'Salidas y sitios de ubicación de extintores sin desorden',
                                    'Clasificación de basuras',
                                    'Estado de Baños',
                                    'PRODUCTOS QUIMICOS',
                                    'Sitios de almacenamiento',
                                    'Hojas de Seguridad de productos quimicos Existentes',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-BOT',
                'nombre'         => 'Inspección de botiquín',
                'categoria'      => 'SST',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Dotación y vigencia de los elementos del botiquín de primeros auxilios.',
                'orden'          => 40,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'UBICACIÓN DEL BOTIQUIN',
                                    'DESCRIPCIÓN DEL ELEMENTO DEL BOTIQUIN DE PRIMEROS AUXILIOS*',
                                    'ALCOHOL ANTISÉPTICO',
                                    'APLICADORES',
                                    'APOSITO O COMRPESAS',
                                    'BAJALENGUAS',
                                    'CURAS',
                                    'ESPARADRAPO DE TELA ROLLO 4"',
                                    'GASAS ESTERILES',
                                    'GUANTES DE LATEX',
                                    'JABÓN QUIRURGICO',
                                    'LINTERNA',
                                    'MASCARILLA RCP',
                                    'MANUAL DE PRIMEROS AUXILIOS',
                                    'PARCHE OCULAR',
                                    'PILAS DE REPUESTO',
                                    'SOLUCIÓN SALINA',
                                    'SULFAPLATA',
                                    'TAPABOCAS',
                                    'TERMOMETRO',
                                    'TIJERAS DE TRAUMA',
                                    'VENDA DE ALGODÓN 3X5 YARDAS',
                                    'VENDA DE ALGODÓN 5X5 YARDAS',
                                    'VENDA ELASTICA 2X5 YARDAS',
                                    'VENDA ELASTICA 3X5 YARDAS',
                                    'VENDA ELASTICA 5X5 YARDAS',
                                    'YODOPAVINA',
                                    'JERINGA',
                                    'SUERO ORAL',
                                    'MENTICOL',
                                    'GEL ANTIBACTERIAL',
                                    'KIT DE EMERGENCIAS',
                                    'CAMILLA EN POLIESTILENO',
                                    'COLLARIN CERVICAL',
                                    'INMOVILIZADOR DE CUELLO PARA CAMILLA',
                                    'INMOVILIZADORES DE EXTREMIDADES',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-GER',
                'nombre'         => 'Inspección gerencial',
                'categoria'      => 'SST',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Recorrido de la alta dirección por las áreas de trabajo.',
                'orden'          => 50,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'DETALLES',
                                    'Las áreas de trabajos están sin escombros, obstáculos, ni basuras',
                                    'Las Escaleras están sin obstáculos',
                                    'Existen zonas destinadas para el almacenamiento de cajas, señalizadas y delimitadas',
                                    'La zona de almacenamiento están organizadas.',
                                    'Existe una zona para el acopio y recolección de residuos, señalizada y delimitada.',
                                    'El acopio está ordenado y aseado.',
                                    'Todas las puertas con cerraduras abren y cierran adecuadamente.',
                                    'Todas las ventanas están en buenas condiciones (limpias y no están rotas).',
                                    'Las herramientas y materiales están identificadas y en su sitio respectivo.',
                                    'Las áreas están limpias y aseadas',
                                    'Los baños están higiénicos y limpios',
                                    'No hay manchas de aceite y grasa en los pisos y corredores.',
                                    'Las oficinas están limpias (paredes, techos, pisos), sin telarañas ni manchas.',
                                    'Las luminarias están limpias libres de polvo e insectos.',
                                    'El Plano de evacuación esta :',
                                    '*Actualizado y legible',
                                    'Los avisos de rutas de evacuación están visibles',
                                    'Debidamente ubicados y Legibles',
                                    'Están todos los avisos de seguridad por producto químico.',
                                    'Todas las puertas o salidas de emergencia están señalizadas',
                                    'Todos los extintores están señalizados',
                                    'El punto(s) de encuentro esta(n) señalizados',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-AMB',
                'nombre'         => 'Inspección ambiental',
                'categoria'      => 'HSEQ',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Manejo de residuos, vertimientos y consumo de recursos.',
                'orden'          => 60,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Gerencia',
                                    'Recurso Humano',
                                    'Logistica',
                                    'Contabilidad',
                                    'Mantenimiento',
                                    'Cafeteria',
                                    'HSEQ',
                                    'CLASIFICACION DE RESIDUOS SOLIDOS EN PUNTOS DE ACOPIO',
                                    'Residuos de Papel en caneca destinada para este residuo',
                                    'Material plástico en caneca destinada para este residuo',
                                    'Residuos de manejo especial en caneca destinada para este residuo',
                                    'Material orgánico en caneca destinada para este residuo',
                                    'Material de vidrio en caneca destinada para este residuo',
                                    'CLASIFICACION DE RESIDUOS PELIGROSOS EN PUNTOS DE ACOPIO',
                                    'Residuos de Epp´S impregnados de hidrocarburos en caneca destinada para este residuo',
                                    'Residuos de pilas y baterias en los sitios y/o canecas destinada para este residuo',
                                    'Tubos fluorescentes en el sitio destinado para este residuo',
                                    'Residuos de botiquin en la caneca destinada para este residuo',
                                    'Monitores y residuos electrónicos en el sitio destinado para este residuo',
                                    'CONSUMO DE PAPEL EFICIENTE',
                                    'Se genera Papel Reciclable',
                                    'Se Reutiliza el papel Reciclable en Fotocopias, Apuntes, otros',
                                    'Se utiliza el papel por las dos caras',
                                    'Se acopia el papel reciclado en buen estado y en orden.',
                                    'DISMINUCION DE CONSUMO DE TINTA',
                                    'Se Utiliza Correo Electronico e Intranet para enviar informacion interna',
                                    'Se Imprime los documentos internos en modo de ahorro de tinta.',
                                    'Se utiliza Cartuchos recargables',
                                    'CONSUMO DE LUZ EFICIENTE',
                                    'Se evidencia luces prendidas innecesarias',
                                    'Se evidencia aires acondicionados prendidos sin necesidad',
                                    'Se Apagan los computadores cuando no se utilizan',
                                    'Se utiliza las lamparas amigables con el ambiente',
                                    'DOCUMENTOS',
                                    'Estan disponibles los registros control de residuos de los RESPEL y RNP',
                                    'Estan en buen estado los equipos eléctricos (MTO)',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-QUIM',
                'nombre'         => 'Inspección de transporte de químicos',
                'categoria'      => 'HSEQ',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Condiciones de seguridad para el transporte de sustancias químicas.',
                'orden'          => 70,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Requisitos del vehiculo',
                                    '¿Se portan en el vehículo mínimo dos extintores multipropósitos?',
                                    '¿Los extintores son revisados y cargados periódicamente?',
                                    '¿El vehículo cuenta con un equipo para la recolección de derrames?',
                                    '¿Se leen y entienden las Hojas de Seguridad antes de realizar la carga y descarga?',
                                    '¿Durante la carga se verifican los documentos y la integridad de los embalajes/envases?',
                                    '¿La carga dentro del vehículo esta debidamente sujeta, de tal forma que no sufra averías?',
                                    '¿Antes de cada recorrido se elabora y entrega al conductor un plan de transporte?',
                                    '¿Se tienen rutas establecidas para el transporte?',
                                    '¿Se cuenta con puestos de control a lo largo de todas las rutas?',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-VIAS',
                'nombre'         => 'Inspección de vías internas',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Estado de las vías internas y sus puntos de conflicto.',
                'orden'          => 80,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'LOSAS',
                                    'PAVIMENTO',
                                    'SEÑALIZACIÓN',
                                    'PARQUEADEROS',
                                    'ZONA DE DESCARGUE',
                                    'ZONA DE CARGUE',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-TRACTO',
                'nombre'         => 'Inspección preoperacional de tractocamión',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Chequeo preoperacional de tractocamión.',
                'orden'          => 110,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    '2. Documentos',
                                    '1. Revisión Técnico Mecánica y Gases',
                                    '2. Registro Único Nacional de Transito (RUNT)',
                                    '3. Licencia de Transito o Tarjeta de Propiedad',
                                    '4. Seguro Obligatorio (SOAT)',
                                    '5. Póliza R.C Extracontractual o Todo riesgo',
                                    '6. Tarjeta de Operación',
                                    '3. Revisión del Vehículo',
                                    'LUCES',
                                    'Altas, Bajas, laterales, Reversa',
                                    'Direccionales, de Stop',
                                    'LLANTAS (Incluye Repuesto)',
                                    'Labrado (min 3mm de huella)',
                                    'Sin cortaduras profundas, sin abultamientos',
                                    'SISTEMA DE FRENOS',
                                    'Fugas de aire',
                                    'Válvula Relay',
                                    'Cámaras',
                                    'Candados y Bandas',
                                    'Freno de Motor',
                                    'TANQUE O CARROCERIA',
                                    'Estado Exterior (pintura, golpes, fracturas)',
                                    'Soportes, muelles y balancines',
                                    'Guardapolvos',
                                    'Línea de vida, Malla Antideslizante, Bicicletero, Registro de Descargue',
                                    'Señalización',
                                    'ACCESORIOS',
                                    'Panorámico',
                                    'Limpia parabrisas',
                                    'Espejos Retrovisores',
                                    'Pito de Reversa, Pitos en general',
                                    'Nivel de fluidos (Motor, Caja de direccion,Bateria, Transmisiones)',
                                    'Sistema de la Dirección',
                                    'Revise Kin Pin quinta rueda (fisuras, deterioro)',
                                    'Patas de anclaje',
                                    'Inspeccione los tanques y líneas de Combustible, no fugas',
                                    'Revise tensión de las correas, no estén rajadas o cristalizadas',
                                    'Revise el estado general de todas las mangueras, conectores, abrazaderas',
                                    'Revise tablero de instrumentación',
                                    'Revise los Cinturones de Seguridad',
                                    'Revise Kit de Carretera (gato,copa,palanca,Llaves, Tacos)',
                                    'Revise kit Contingencia, Botiquín, Extintores',
                                    'VIERNES',
                                    'EQUIPO DE BOMBEO',
                                    'Moto bomba',
                                    'Acoples',
                                    'estado del yoyo',
                                    'Estado de la base de sostenimiento de la Moto bomba',
                                    'Presenta fugas de aceite o combustible',
                                    'Estado del caracol',
                                    'LUNES',
                                    'MARTES',
                                    'MIERCOLES',
                                    'JUEVES',
                                    'SABADO',
                                    'DOMINGO',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-BUS',
                'nombre'         => 'Inspección preoperacional de bus o buseta',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Chequeo preoperacional de bus o buseta.',
                'orden'          => 120,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Califique: B: bueno M: Mal estado NT: No tiene NA: No aplica',
                                    'MOTOR',
                                    'Nivel de aceite y estado',
                                    'Nivel de refrigerante y estado',
                                    'Nivel de agua parabrisas',
                                    'Nivel de fluido de frenos y estado',
                                    'Tapa de radiador',
                                    'Soporte de batería',
                                    'Estado de bornes',
                                    'Cables sueltos o sin aislamiento',
                                    'LUCES',
                                    'Luces bajas',
                                    'Luces altas',
                                    'Luces internas',
                                    'Direccionales',
                                    'Faros direccionales',
                                    'Faros posteriores',
                                    'Faros neblineros',
                                    'Faros de parqueo',
                                    'ACCESORIOS DE SEGURIDAD',
                                    'malla antideslizante del pasillo',
                                    'cornetas',
                                    'pito',
                                    'Bocina de retroceso',
                                    'Cable de batería',
                                    'Triangulo de seguridad',
                                    'tacos del vehículo',
                                    'Llantas',
                                    'Llantas de repuesto fija',
                                    'Llantas y rines (Labrado 2mm Livianos, 3mm Pesados)*',
                                    'Fecha vencimiento SOAT:',
                                    'CONDUCTOR FIRMA',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-LIVIANO',
                'nombre'         => 'Inspección preoperacional de vehículo liviano',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Chequeo preoperacional de vehículo liviano.',
                'orden'          => 130,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Licencia de transito (Tarjeta de propiedad del vehículo) *',
                                    'SOAT y seguro extracontractual *',
                                    'Revisión Tecno mecánica y de Gases *',
                                    'Licencia de Conducción Legal y Vigente *',
                                    'Certificación en manejo Defensivo',
                                    'Afiliación a EPS, ARP *',
                                    'Pasado Judicial Vigente',
                                    'GPS *',
                                    'Inducción del Conductor',
                                    'Sistema dirección *',
                                    'Sistema de admisión *',
                                    'Sistema de enfriamiento *',
                                    'Sistema de alimentación *',
                                    'Sistema de lubricación *',
                                    'Sistema de escape *',
                                    'Alternador',
                                    'Arranque',
                                    'Estado y sujeción de las baterías (bornes y cables)',
                                    'Luces Frontales *',
                                    'Cocuyos *',
                                    'Luces Direccionales *',
                                    'Luces Estacionarias *',
                                    'Luz de reverso *',
                                    'Luz interior cabina *',
                                    'Luz tablero de instrumentos *',
                                    'Stops *',
                                    'Alarma de Reverso *',
                                    'Freno de Servicio, Emergencia *',
                                    'Estado de Adbestos *',
                                    'Direccionales *',
                                    'Tracción',
                                    'Repuesto con aire',
                                    'Estado general de latonería y Pintura',
                                    'Puertas en buen estado de Cierre y Bloqueo',
                                    'Espejos Laterales',
                                    'Tanques de Combustible (Sujeción y estado sin goteo)',
                                    'Vidrio Frontal y limpia brisas *',
                                    'Cinturón de seguridad en todos los asientos',
                                    'Estado de la tapicería',
                                    'Luz de techo',
                                    'Linterna con pilas anti chispa',
                                    'Conos Reflectivos',
                                    'Chaleco Reflectivo',
                                    'Gato con Palanca',
                                    'Kit de llaves',
                                    'Calibrado de Llantas',
                                    'Copa de ruedas',
                                    'Hombre solo',
                                    'Llave expansiva',
                                    'Destornillador Estrella',
                                    'Destornillador Pala',
                                    'Alicate',
                                    'Caja de Repuesto',
                                    'Gasa',
                                    'Curas',
                                    'Vendas Elástico 4 x 5 yardas',
                                    'Agua Oxigenada o Isodene',
                                    'Esparadrapo',
                                    'Guantes Quirúrgicos',
                                    'Extintor de 10 lb.',
                                    'Kit de contingencia',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-MOTO',
                'nombre'         => 'Inspección preoperacional de motocicleta',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Chequeo preoperacional de motocicleta, incluidos los EPP del motociclista.',
                'orden'          => 140,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'CASCO',
                                    'GUANTES',
                                    'BOTAS',
                                    'IMPERMEABLE',
                                    'GAFAS',
                                    'CHALECO',
                                    'DIRECCION',
                                    'DIRECCIONALES',
                                    'PITO',
                                    'NIVEL DE COMBUSTIBLE',
                                    'NIVEL DE ACEITE',
                                    'ESTADO Y FUNCIONAMIENTO DE LUCES',
                                    'MANILARES',
                                    'GUARDABARROS',
                                    'CHASIS',
                                    'SUSPENSION',
                                    'FRENOS',
                                    'LLANTAS',
                                    'RINES',
                                    'TREN DE ARRASTRE',
                                    'EMBRAGUE',
                                    'EXOSTO',
                                    'RETROVISORES',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-BICI',
                'nombre'         => 'Inspección preoperacional de bicicleta',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Chequeo preoperacional de bicicleta.',
                'orden'          => 150,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Llantas',
                                    'Sujetadores de llantas',
                                    'Frenos',
                                    'Cadena',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-CISTERNA',
                'nombre'         => 'Inspección preoperacional de vehículo cisterna',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Chequeo preoperacional de vehículo cisterna.',
                'orden'          => 160,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Estado cabina (S.P)',
                                    'Estado silla y apoyacabeza del conductor (S.P)',
                                    'Cinturón de seguridad 3 puntos para conductor y pasajero (S.P)',
                                    'Manometros e indicadores del tablero, panel de instrumentos(S.A)',
                                    'Panorámico (S.P)',
                                    'Limpia brisas, plumillas (S.P)',
                                    'Accesorios y millare(radio, equipo adicional cabina)(S.P)',
                                    'UNIDAD GPS (S.P)',
                                    'Espejos retrovisores y auxiliares (S.A)',
                                    'Aire acondicionado (S.A)',
                                    'Chapas, puertas, tapicería (S.P)',
                                    'Guarda fangos y guardabarros (S.P)',
                                    'Estribos, tapa baterias, Parrillas______unid. (S.P)',
                                    'Apariencia Exterior de cabina (S.P)',
                                    'Baterias y conexiones electricas cubiertas (S.A)',
                                    'Sistema de encendido y apagado (alternador, arranque) (S.A)',
                                    'Cable 7 vias (S.A)',
                                    'Interruptor electrico Central (master) (S.P)',
                                    'Luces(unidades, cocuyos, licuadoras, stops) (S.A)',
                                    'Pito eléctrico y alarmas de reversa (S.A)',
                                    'Instalaciones eléctricas del motor, sensores y modulo (S.A)',
                                    'Freno de motor (S.A)',
                                    'Soportes de motor (S.P)',
                                    'Radiador, ventilador, intercooler (S.P)',
                                    'Turbo-compresor, mangueras admisión (S.A)',
                                    'Tapas y varilla medidora aceite (S.A)',
                                    'Tanque de combustibles, pescadores, mangueras (S.A)',
                                    'Sistema de escape, exosto, flexibles, (S.P)',
                                    'Dirección, timon, caña dirección, crucetas (S.A)',
                                    'Caja de dirección, terminales, splinders y barra transversal (S.A)',
                                    'Bomba hidraulica, deposito hidraulico y mangueras (S.A)',
                                    'Muelles, hojas de resorte, balancines, bujes (S.A)',
                                    'Bombonas, valvulas niveladoras (suspensión neumatica) (S.A)',
                                    'Vigas, tensoras, bujes (S.A)',
                                    'Amortiguadores (S.A)',
                                    'Chasis (S.P)',
                                    'Freno de servicio (S.A)',
                                    'Freno de seguridad (S.A)',
                                    'Bandas(7mm min.), campanas, levas (S.A)',
                                    'Camaras de freno, lineas de aire, (S.A)',
                                    'Sist. Neumatico:Compresor, secador, tanques de aire (S.A)',
                                    'Valvulas Relay (S.A)',
                                    'Embrague (S.A)',
                                    'Cardan, Kit centro cardan, crucetas (S.P)',
                                    'Transmision de cambios (S.P)',
                                    'Diferenciales (S.P)',
                                    'Ejes, retenedores (S.P)',
                                    'RINES CABEZOTE: __________ en aluminio, ________ en lamina (S.A)',
                                    'RINES TRAILER: _________ en aluminio, __________ en lamina (S.A)',
                                    'Quinta rueda ( seguros, ajuste, surcos de lubricación) (S.P)',
                                    'Hombros o base escualizable(compensadora) (S.P)',
                                    'tornillos sujeción tornamesa (S.P)',
                                    'King Pin (S.P)',
                                    '(S.A)',
                                    'Estado general del tanque (S.P)',
                                    'Línea de vida (S.P)',
                                    'Manholes, empaques,cortinas (escotillas) y valvulas de venteo (S.P)',
                                    'Drenaje de la pasarela (S.P)',
                                    'Malla antideslizante en pasarela (S.P)',
                                    'Chasis protector de válvula de descargue, batea (S.P)',
                                    'Válvula de descargue con tapa, valvula drenaje (S.P)',
                                    'Defensa trasera sobresaliente (S.P)',
                                    'Tornillos, mariposas y huecos para precintos (S.P)',
                                    'Pernos para conexión a tierra (S.P)',
                                    'Patas de apoyo tanque, EJE RETRACTIL (S.P)',
                                    'Bicicleteros y escalera (S.P)',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-ENTREGA',
                'nombre'         => 'Inspección de entrega de vehículo',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Estado del vehículo al entregarlo o recibirlo de un conductor.',
                'orden'          => 170,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Licencia De Transito',
                                    'Seguro Obligatorio',
                                    'Revisión Tecno mecánica',
                                    'Registro Semiremolque',
                                    'Tabla Aforo',
                                    'Carpeta o Folder HSEQ Actualizado',
                                    'Tarjetas de Ruta',
                                    'Tarjeta emergencia producto transportado',
                                    'Resoluciones de aprobación del PDC',
                                    'Pasaporte vigente',
                                    'Llaves Del Vehiculo',
                                    'Llaves Tapa Tanque',
                                    'Barrera absorbente de 5^x 10¨',
                                    'Tela oleofílica de 19¨x17¨-Grueso 3/8¨.',
                                    'Absorbente Biodegradable',
                                    'Desengrasante Biodegradable',
                                    'Bolsas plásticas industrial Negra-Roja-Verde',
                                    'Bolsas de propileno (Lonas)',
                                    'Plástico grueso calibre 5',
                                    'Cinta de Señalización de Seguridad',
                                    'Manila 3/4',
                                    'Calajanes de Madera',
                                    'Alambre Dulce calibre 14',
                                    'Tivek',
                                    'Balde plástico/ caneca',
                                    'Protector respiratorio de gases y sus Filtros',
                                    'Pica con cabo',
                                    'Pala con cabo',
                                    'Pala plástica',
                                    'Conos de 90 cm REFLECTIVOS',
                                    'Extintor de 20 Libras Tanque',
                                    'Extintor de 20 libras Cabezote',
                                    'Tacos de Madera',
                                    'Motobomba (si aplica)',
                                    'Paleta de "PARE - SIGA"',
                                    'Martillo de goma / caucho',
                                    'Linterna de seguridad (encauchetada)',
                                    'Cortador Industrial / Machete / Segueta',
                                    'Chaleco reflectivo',
                                    'Gato para capacidad del vehículo',
                                    'Copa de ruedas y palanca',
                                    'Alicate',
                                    'Juego destornilladores (estrella - pala)',
                                    'Juego llaves mixtas',
                                    'Calibrador aire llantas',
                                    'Manguera de aire 15 mts',
                                    'Llave Expansiva',
                                    'Hombre solo',
                                    'Linterna',
                                    'Casco',
                                    'Barbuquejo',
                                    'Guantes de nitrilo',
                                    'Guantes Vaqueta',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-INS-ASEO-VEH',
                'nombre'         => 'Inspección de orden y aseo del vehículo',
                'categoria'      => 'PESV',
                'grupo'          => 'inspeccion',
                'descripcion'    => 'Orden, aseo y elementos obligatorios dentro del vehículo.',
                'orden'          => 180,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'placa', 'label' => 'Placa', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'conductor', 'label' => 'Conductor', 'tipo' => 'text'],
                                ['key' => 'kilometraje', 'label' => 'Kilometraje', 'tipo' => 'number'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'NOMBRE DEL CONDUCTOR:',
                                    'ITEM/CALIFICACION (SI - NO)',
                                    'Epp´s',
                                    'Documentos del vehículo',
                                    'Documentos del viaje',
                                    'Carpeta del conductor',
                                    'Maleta de viaje',
                                    'Extintor de cabina',
                                    'Botiquín',
                                    'Bolsa para los residuos de la cabina',
                                    'Herramienta',
                                    'Gato',
                                    'Manguera de aire',
                                    'Conos',
                                    'Kit de contingencia',
                                    'ITEM/CALIFICACION (SI-NO)',
                                    'Tapetes limpios',
                                    'Interior de la cabina limpia',
                                    'Elimina los residuos de la bolsa en las canecas respectivas',
                                    'Exterior de cabina limpia',
                                    'Remolque limpio',
                                    'Motor limpio',
                                    'Realiza lavada general mínimo una vez al mes',
                                    'Realiza juagada mínimo cada dos viajes',
                                    'INSPECCIONADO POR',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-LCH-FATIGA',
                'nombre'         => 'Lista de chequeo de somnolencia y fatiga',
                'categoria'      => 'PESV',
                'grupo'          => 'lista',
                'descripcion'    => 'Autorreporte del conductor antes de iniciar el turno.',
                'orden'          => 210,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'A dormido menos de 6 hr. En las ultimas 24 horas?',
                                    'Tiene alguna condición fisica y/o psicológica que le impida conducir y/o operar hoy?',
                                    'Durante su descanso ingerio bebidas alcohólicas y no han pasado mas de 24 horas?',
                                    'Tiene algún malestar o enfermedad que le dificulte conducir?',
                                    'Tiene dificultad para concentrarse o poner atención a las tareas?',
                                    'A conducido mas de 8 horas seguidas en las ultimas 12 horas?',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-LCH-SIMULACRO',
                'nombre'         => 'Lista de chequeo de simulacro',
                'categoria'      => 'SST',
                'grupo'          => 'lista',
                'descripcion'    => 'Evaluación del simulacro de emergencia.',
                'orden'          => 220,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    '¿La realización del simulacro fue a la hora indicada?',
                                    '¿El personal desalojo el inmueble de manera ordenada, rápida y segura?',
                                    'El personal sale del inmueble:',
                                    ' Fumando',
                                    ' Bromeando',
                                    ' Apático',
                                    ' Distraído',
                                    ' Nervioso',
                                    ' Mostraron interés por el simulacro',
                                    '¿El personal sigue las rutas de evacuación establecidas?',
                                    '¿El personal llegó al punto de encuentro sin problemas?',
                                    '¿Alguna persona no siguió la ruta de evacuación?',
                                    'Situaciones adversas reales',
                                    ' Personas lesionadas',
                                    ' Daños en bienes',
                                    ' Colapso de la movilidad en el sector',
                                    'Otras, ¿Cuáles?',
                                    'EVALUACION DE BRIGADISTAS Y COORDINADORES',
                                    '¿Los brigadistas portan identificación o distintivos?',
                                    '¿Los brigadistas realizaron el censo del personal a su cargo?',
                                    '¿Asumieron liderazgo oportuno, firme y adecuado?',
                                    '¿En general se notó la presencia de brigadistas y coordinadores de evacuación?',
                                    '¿Utilizaron lenguaje adecuado al dirigirse a los demás?',
                                    '¿Actuaron con serenidad?',
                                    '¿Actuaron con firmeza?',
                                    '¿Daban instrucciones claras?',
                                    '¿Guiaron adecuadamente al grupo durante la evacuación?',
                                    'DESCRIPCIÓN DE LA ZONA AL FINALIZAR EL SIMULACRO',
                                    'HORA DE REPORTE:',
                                    'DATOS DEL COORDINADOR DE ARL O BRIGADISTA Nombre: Entidad: Teléfono de contacto:',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-LCH-PERS',
                'nombre'         => 'Lista de chequeo de documentos del personal',
                'categoria'      => 'PESV',
                'grupo'          => 'lista',
                'descripcion'    => 'Verificación documental del conductor y su vigencia.',
                'orden'          => 230,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'REQUERIMIENTO',
                                    'Entrega certificado de afiliación vigente a salud y pensiones',
                                    'Entrega carta de intención de afiliarse o no a la ARL',
                                    'Si requiere tener subcontratistaas, se exige los mismos documentos a estos',
                                    'Copia de los planillas de pago a EPS, AFP y ARL',
                                    'Usan ropa adecuada y EPP acordes a la actividad y factores de riesgo presentes',
                                    'Reporta los accidentes de trabajo a su respectiva ARL',
                                    'Cumplimiento de los requisitos legales aplicables',
                                    'Infracciones en los ultimos 3 meses',
                                    'Asiste a las capacitaciones en seguridad vial realizadas por la empresa',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-LCH-AUD',
                'nombre'         => 'Lista de chequeo de auditoría interna',
                'categoria'      => 'HSEQ',
                'grupo'          => 'lista',
                'descripcion'    => 'Lista de verificación para la auditoría interna del sistema de gestión.',
                'orden'          => 240,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Datos generales',
                            'campos' => [
                                ['key' => 'responsable_inspeccion', 'label' => 'Responsable de la inspección', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'cargo', 'label' => 'Cargo', 'tipo' => 'text'],
                                ['key' => 'sede', 'label' => 'Sede / área', 'tipo' => 'text'],
                            ],
                        ],
                        [
                            'titulo' => 'Verificación',
                            'campos' => [
                                ['key' => 'items', 'label' => 'Aspectos a verificar', 'tipo' => 'checklist', 'items' => [
                                    'Asignación de una persona que diseñe e implemente el Sistema de Gestión de SST - PESV',
                                    'Asignación de responsabilidades en SST - PESV',
                                    'Asignación de recursos para el Sistema de Gestión en SST - PESV',
                                    'Afiliación al Sistema de Seguridad Social Integral',
                                    'Conformación y funcionamiento del COPASST',
                                    'Capacitación de los integrantes del COPASST',
                                    'Conformación y funcionamiento del Comité de Convivencia Laboral',
                                    'Programa de capacitación anual',
                                    'Inducción y reinducción en SST',
                                    'Curso Virtual de capacitación de cincuenta (50) horas en SST.',
                                    'Política de Seguridad y Salud en el Trabajo.',
                                    'Objetivos de SST',
                                    'Evaluación Inicial del Sistema de Gestión',
                                    'Plan Anual de Trabajo',
                                    'Archivo y retención documental del Sistema de Gestión de SST',
                                    'Rendición de cuentas',
                                    'Mecanismos de comunicación',
                                    'Identificación y evaluación para la adquisición de bienes y servicios',
                                    'Evaluación y selección de proveedores y contratistas',
                                    'Gestión del cambio',
                                    'Actividades de medicina del trabajo y de prevención y promoción de la Salud.',
                                    'Perfiles de cargos',
                                    'Evaluaciones médicas ocupacionales',
                                    'Custodia de las historias clínicas',
                                    'Restricciones y recomendaciones médico laborales',
                                    'Estilos de vida y entorno saludable',
                                    'Servicios de higiene',
                                    'Manejo de Residuos',
                                    'Reporte de accidentes de trabajo y enfermedades laborales',
                                    'Registro y análisis estadístico de accidentes de trabajo y enfermedades laborales',
                                    'Frecuencia de accidentalidad',
                                    'Severidad de accidentalidad',
                                    'Proporción de accidentes de trabajo mortales',
                                    'Prevalencia de la enfermedad laboral',
                                    'Incidencia de la enfermedad laboral',
                                    'Ausentismo por causa médica',
                                    'Metodología para identificación de peligros, evaluación y valoración de riesgos',
                                    'Identificación de sustancias catalogadas como carcinógenas o con toxicidad aguda',
                                    'Mediciones ambientales',
                                    'Medidas de prevención y control frente a peligros/riesgos identificados',
                                    'Aplicación de medidas de prevención y control por parte de los trabajadores',
                                    'Procedimientos e instructivos internos de seguridad y salud en el trabajo',
                                    'Inspecciones a instalaciones, maquinaria o equipos',
                                    'Mantenimiento periódico de las instalaciones, equipos, máquinas y herramientas',
                                    'Entrega de los elementos de protección personal – EPP y capacitación en uso adecuado',
                                    'Plan de prevención, preparación y respuesta ante emergencias',
                                    'Brigada de prevención, preparación y respuesta ante emergencias',
                                    'Definición de indicadores del Sistema de Gestión de Seguridad y Salud en el Trabajo',
                                    'Auditoría anual',
                                    'Revisión por la alta dirección. Alcance de la auditoría del Sistema de Gestión de SST',
                                    'Revicion por la Direccion con el COPASST',
                                    'Acciones preventivas y/o correctivas',
                                    'Acciones de mejora conforme a revisión de la Alta Dirección',
                                    'Plan de mejoramiento',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Cierre',
                            'campos' => [
                                ['key' => 'observaciones', 'label' => 'Observaciones generales', 'tipo' => 'textarea'],
                                ['key' => 'acciones', 'label' => 'Acciones correctivas propuestas', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Inspector', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-ACTA-REU',
                'nombre'         => 'Acta de reunión',
                'categoria'      => 'SST',
                'grupo'          => 'acta',
                'descripcion'    => 'Reunión ordinaria del sistema de gestión.',
                'orden'          => 310,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Convocatoria',
                            'campos' => [
                                ['key' => 'lugar', 'label' => 'Lugar', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'hora_inicio', 'label' => 'Hora de inicio', 'tipo' => 'text'],
                                ['key' => 'hora_fin', 'label' => 'Hora de finalización', 'tipo' => 'text'],
                                ['key' => 'objetivo', 'label' => 'Objetivo de la reunión', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'asistentes', 'label' => 'Convocados y asistentes (nombre, cargo, firma)', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Agenda',
                            'campos' => [
                                ['key' => 'agenda', 'label' => 'Orden del día', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Desarrollo y compromisos',
                            'campos' => [
                                ['key' => 'desarrollo', 'label' => 'Desarrollo de la agenda', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'compromisos', 'label' => 'Tareas y compromisos (qué, quién, para cuándo)', 'tipo' => 'textarea'],
                                ['key' => 'pendientes', 'label' => 'Pendientes de la reunión anterior', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Quien preside', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-ACTA-GER',
                'nombre'         => 'Acta de reunión gerencial',
                'categoria'      => 'HSEQ',
                'grupo'          => 'acta',
                'descripcion'    => 'Reunión de la alta dirección.',
                'orden'          => 320,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Convocatoria',
                            'campos' => [
                                ['key' => 'lugar', 'label' => 'Lugar', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'hora_inicio', 'label' => 'Hora de inicio', 'tipo' => 'text'],
                                ['key' => 'hora_fin', 'label' => 'Hora de finalización', 'tipo' => 'text'],
                                ['key' => 'objetivo', 'label' => 'Objetivo de la reunión', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'asistentes', 'label' => 'Convocados y asistentes (nombre, cargo, firma)', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Agenda',
                            'campos' => [
                                ['key' => 'agenda', 'label' => 'Orden del día', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Desarrollo y compromisos',
                            'campos' => [
                                ['key' => 'desarrollo', 'label' => 'Desarrollo de la agenda', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'compromisos', 'label' => 'Tareas y compromisos (qué, quién, para cuándo)', 'tipo' => 'textarea'],
                                ['key' => 'pendientes', 'label' => 'Pendientes de la reunión anterior', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Quien preside', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-ACTA-COPASST',
                'nombre'         => 'Acta de reunión del COPASST',
                'categoria'      => 'SST',
                'grupo'          => 'acta',
                'descripcion'    => 'Reunión ordinaria del Comité Paritario de Seguridad y Salud en el Trabajo.',
                'orden'          => 330,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Convocatoria',
                            'campos' => [
                                ['key' => 'lugar', 'label' => 'Lugar', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'hora_inicio', 'label' => 'Hora de inicio', 'tipo' => 'text'],
                                ['key' => 'hora_fin', 'label' => 'Hora de finalización', 'tipo' => 'text'],
                                ['key' => 'objetivo', 'label' => 'Objetivo de la reunión', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'asistentes', 'label' => 'Convocados y asistentes (nombre, cargo, firma)', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Agenda',
                            'campos' => [
                                ['key' => 'agenda', 'label' => 'Puntos tratados', 'tipo' => 'checklist', 'items' => [
                                    'Verificación del quórum',
                                    'Lectura del acta anterior',
                                    'Seguimiento a compromisos',
                                    'Reporte de actos y condiciones inseguras',
                                    'Investigación de accidentes del periodo',
                                    'Proposiciones y varios',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Desarrollo y compromisos',
                            'campos' => [
                                ['key' => 'desarrollo', 'label' => 'Desarrollo de la agenda', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'compromisos', 'label' => 'Tareas y compromisos (qué, quién, para cuándo)', 'tipo' => 'textarea'],
                                ['key' => 'pendientes', 'label' => 'Pendientes de la reunión anterior', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Quien preside', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-ACTA-ENTREGA',
                'nombre'         => 'Acta de entrega',
                'categoria'      => 'HSEQ',
                'grupo'          => 'acta',
                'descripcion'    => 'Entrega formal de un bien, cargo o documento.',
                'orden'          => 340,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Convocatoria',
                            'campos' => [
                                ['key' => 'lugar', 'label' => 'Lugar', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'hora_inicio', 'label' => 'Hora de inicio', 'tipo' => 'text'],
                                ['key' => 'hora_fin', 'label' => 'Hora de finalización', 'tipo' => 'text'],
                                ['key' => 'objetivo', 'label' => 'Objetivo de la reunión', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'asistentes', 'label' => 'Convocados y asistentes (nombre, cargo, firma)', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Agenda',
                            'campos' => [
                                ['key' => 'agenda', 'label' => 'Orden del día', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Desarrollo y compromisos',
                            'campos' => [
                                ['key' => 'desarrollo', 'label' => 'Desarrollo de la agenda', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'compromisos', 'label' => 'Tareas y compromisos (qué, quién, para cuándo)', 'tipo' => 'textarea'],
                                ['key' => 'pendientes', 'label' => 'Pendientes de la reunión anterior', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Quien preside', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-ACTA-AUD-APER',
                'nombre'         => 'Acta de apertura de auditoría',
                'categoria'      => 'HSEQ',
                'grupo'          => 'acta',
                'descripcion'    => 'Apertura de la auditoría interna.',
                'orden'          => 350,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Convocatoria',
                            'campos' => [
                                ['key' => 'lugar', 'label' => 'Lugar', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'hora_inicio', 'label' => 'Hora de inicio', 'tipo' => 'text'],
                                ['key' => 'hora_fin', 'label' => 'Hora de finalización', 'tipo' => 'text'],
                                ['key' => 'objetivo', 'label' => 'Objetivo de la reunión', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'asistentes', 'label' => 'Convocados y asistentes (nombre, cargo, firma)', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Agenda',
                            'campos' => [
                                ['key' => 'agenda', 'label' => 'Puntos tratados', 'tipo' => 'checklist', 'items' => [
                                    'Presentación del equipo auditor',
                                    'Alcance y criterios de la auditoría',
                                    'Plan y horario',
                                    'Reglas de confidencialidad',
                                    'Proposiciones y varios',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Desarrollo y compromisos',
                            'campos' => [
                                ['key' => 'desarrollo', 'label' => 'Desarrollo de la agenda', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'compromisos', 'label' => 'Tareas y compromisos (qué, quién, para cuándo)', 'tipo' => 'textarea'],
                                ['key' => 'pendientes', 'label' => 'Pendientes de la reunión anterior', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Quien preside', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'codigo'         => 'FT-ACTA-AUD-CIERRE',
                'nombre'         => 'Acta de cierre de auditoría',
                'categoria'      => 'HSEQ',
                'grupo'          => 'acta',
                'descripcion'    => 'Cierre de la auditoría interna.',
                'orden'          => 360,
                'schema' => [
                    'secciones' => [
                        [
                            'titulo' => 'Convocatoria',
                            'campos' => [
                                ['key' => 'lugar', 'label' => 'Lugar', 'tipo' => 'text', 'requerido' => true],
                                ['key' => 'hora_inicio', 'label' => 'Hora de inicio', 'tipo' => 'text'],
                                ['key' => 'hora_fin', 'label' => 'Hora de finalización', 'tipo' => 'text'],
                                ['key' => 'objetivo', 'label' => 'Objetivo de la reunión', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'asistentes', 'label' => 'Convocados y asistentes (nombre, cargo, firma)', 'tipo' => 'textarea'],
                            ],
                        ],
                        [
                            'titulo' => 'Agenda',
                            'campos' => [
                                ['key' => 'agenda', 'label' => 'Puntos tratados', 'tipo' => 'checklist', 'items' => [
                                    'Fortalezas',
                                    'Observaciones',
                                    'No conformidades',
                                    'Proposiciones y varios',
                                ]],
                            ],
                        ],
                        [
                            'titulo' => 'Desarrollo y compromisos',
                            'campos' => [
                                ['key' => 'desarrollo', 'label' => 'Desarrollo de la agenda', 'tipo' => 'textarea', 'requerido' => true],
                                ['key' => 'compromisos', 'label' => 'Tareas y compromisos (qué, quién, para cuándo)', 'tipo' => 'textarea'],
                                ['key' => 'pendientes', 'label' => 'Pendientes de la reunión anterior', 'tipo' => 'textarea'],
                                ['key' => 'firma', 'label' => 'Quien preside', 'tipo' => 'firma'],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}
