<?php

namespace Database\Seeders;

use App\Models\ManagementProgram;
use Illuminate\Database\Seeder;

/**
 * Catálogo de programas de gestión, sacado de las hojas de programas de los
 * Excel de CMK («4.2.1 PVE Ergonomia», «8. PROGRAMA FATIGA», «8. PROGRAMA DE
 * VELOCIDAD», «Programa prev. distracción», «8. PROGRAMA DE PREV. ACTORES VI»,
 * «4.2.1 alcohol» y «4.2.1 Programa G. Ambiental» del libro SST-PESV, y
 * «8.1 PVE FOMENTOS» del libro SGI).
 *
 * Las actividades y los meses programados salen tal cual del cronograma de
 * cada hoja. Los indicadores se transcribieron a mano: el Excel escribe la
 * meta en prosa («Generar el cierre del 90 % de los hallazgos») y aquí hace
 * falta un número y un sentido. Donde el Excel no da una meta numérica
 * coherente con la fórmula, se deja `meta` nula y se conserva su texto.
 *
 * Idempotente: se puede volver a correr. Solo toca el catálogo, nunca los
 * programas ya adoptados por las empresas, que guardan su propia copia.
 */
class ManagementProgramsSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->programas() as $i => $p) {
            ManagementProgram::updateOrCreate(['codigo' => $p['codigo']], [
                'nombre' => $p['nombre'],
                'categoria' => $p['categoria'],
                'objetivo' => $p['objetivo'],
                'alcance' => $p['alcance'],
                'recursos' => $p['recursos'],
                'formato_codigo' => $p['formato'],
                'actividades' => $p['actividades'],
                'indicadores' => $p['indicadores'],
                'orden' => $i + 1,
            ]);
        }
    }

    /** @return list<array<string, mixed>> */
    private function programas(): array
    {
        return [
            [
                'codigo' => 'PR-SST-04',
                'nombre' => 'PVE para la prevención de alteraciones osteomusculares',
                'categoria' => 'pve',
                'objetivo' => 'Prevenir la aparición de desórdenes músculo esqueléticos a través de la identificación, evaluación e intervención de las condiciones no ergonómicas encontradas en los puestos de trabajo, con el fin de mejorar las condiciones de salud y trabajo de la población laboralmente expuesta.',
                'alcance' => 'La población objeto del programa está conformada por los trabajadores de la empresa que estén o vayan a estar expuestos a los agentes de riesgo por condiciones no ergonómicas en los puestos de trabajo.',
                'recursos' => 'Económicos, Técnicos, Humanos, Infraestructura',
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Planeación y programación de las actividades a ejecutar en el año',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [3, 6, 12],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer los mecanismos para controlar el riesgo',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [1, 2, 3, 6, 8, 12],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer indicadores de gestión',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [1, 2, 6],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Ejecución Inspecciones puestos de trabajo en áreas que requieren fase diagnósticas',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [1, 2, 3],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Aplicación encuesta de sintomatología a funcionarios en áreas que requieren fase diagnósticas',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [2],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Valoraciones osteomusculares',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Inspecciones a puestos de trabajo en oficinas y/o áreas administrativas de casos especiales',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [2],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Aplicación de encuesta de sintomatología a funcionarios en oficinas y/o áreas administrativas de casos especiales',
                        'responsable' => 'Coordinador HSE',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación sobre lesiones osteo musculares (las más frecuentes y manejo de cada una)',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en estilos de vida saludable',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en higiene postural intra y extra laboral',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Programación y ejecución de escuela de Relajación para funcionarios',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Programación y ejecución de escuela de Ergonomía en ciudades determinadas',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Programación y ejecución de Pausas activas para funcionarios',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Rumboterapia',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Asesoría en programación de fase de seguimiento del SVE osteo muscular',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [12],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a cumplimiento de programación actividades de seguimiento',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a Indicadores',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a las acciones tomadas frente a los hallazgos',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [12],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Implementación de acciones correctivas y preventivas. / correctivos',
                        'responsable' => 'COORDINADOR SST',
                        'meses' => [],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'cobertura',
                        'nombre' => 'Cobertura',
                        'numerador' => 'Trabajadores que participan en la actividad',
                        'denominador' => 'Trabajadores programados',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'eficacia',
                        'nombre' => 'Eficacia',
                        'numerador' => 'Recomendaciones cerradas',
                        'denominador' => 'Total de recomendaciones',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'prevalencia',
                        'nombre' => 'Prevalencia',
                        'numerador' => 'Casos nuevos + casos antiguos',
                        'denominador' => 'Trabajadores expuestos',
                        'meta' => 0,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'incidencia',
                        'nombre' => 'Incidencia',
                        'numerador' => 'Casos nuevos',
                        'denominador' => 'Trabajadores expuestos',
                        'meta' => 0,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                    ],
                ],
            ],
            [
                'codigo' => 'PVE-FOMENTOS',
                'nombre' => 'PVE de fomento de estilos de vida y trabajo saludable',
                'categoria' => 'pve',
                'objetivo' => 'Contribuir al mejoramiento de la calidad de vida de los trabajadores y la productividad de la empresa, mediante la promoción de estilos de vida y trabajo saludables.',
                'alcance' => 'Todos los trabajadores de la empresa.',
                'recursos' => 'Económicos, Técnicos, Humanos',
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Verificación y Actualización Matriz de Identificación de peligros, evaluación y control de riesgos en aquellas actividades que involucran Riesgo Biológico',
                        'responsable' => 'Responsable SST',
                        'meses' => [1, 8],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Revisar causas de accidentalidad, de consultas médicas y/o de de ausentismo por enfermedad común',
                        'responsable' => 'Responsable SST',
                        'meses' => [2, 4, 6, 8, 10, 12],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Divulgación PVE Fomentos de Estilos de Vida y Trabajo Saludable',
                        'responsable' => 'Responsable SST',
                        'meses' => [2, 8],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación Enfermedades epidemiológicas',
                        'responsable' => 'Responsable SST',
                        'meses' => [4, 7],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación hábitos de vida saludable',
                        'responsable' => 'Responsable SST',
                        'meses' => [3, 9],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación prevención del consumo de Alcohol, drogas y/o sustancias psicoactivas (cigarrillo)',
                        'responsable' => 'Responsable SST',
                        'meses' => [6, 12],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Tamizaje cardiovascular (peso, talla )',
                        'responsable' => 'Responsable SST',
                        'meses' => [4],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación prevención y causalidad el sobre peso y obesidad',
                        'responsable' => 'Responsable SST',
                        'meses' => [5],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación planificación familiar',
                        'responsable' => 'Responsable SST',
                        'meses' => [6],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación prevención de enfermedades e infecciones de transmisión sexual',
                        'responsable' => 'Responsable SST',
                        'meses' => [7],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Realizar el seguimiento medición de indicadores semestralmente',
                        'responsable' => 'Responsable SST',
                        'meses' => [7, 12],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Definir y/o realizar acciones de mejora',
                        'responsable' => 'Responsable SST',
                        'meses' => [8, 12],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'cobertura',
                        'nombre' => 'Cobertura',
                        'numerador' => 'Trabajadores que participaron en el programa',
                        'denominador' => 'Trabajadores programados para participar',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'incidencia',
                        'nombre' => 'Incidencia',
                        'numerador' => 'Casos nuevos con diagnóstico de patología común',
                        'denominador' => 'Trabajadores expuestos',
                        'meta' => 0,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'prevalencia',
                        'nombre' => 'Prevalencia',
                        'numerador' => 'Casos nuevos y antiguos de patología común',
                        'denominador' => 'Trabajadores expuestos',
                        'meta' => 0,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                    ],
                ],
            ],
            [
                'codigo' => 'PR-SST-07',
                'nombre' => 'Programa de prevención del consumo de alcohol y sustancias psicoactivas',
                'categoria' => 'pesv',
                'objetivo' => 'Diseñar e implementar estrategias de intervención encaminadas a controlar los peligros asociados al consumo de alcohol y sustancias psicoactivas, con cero tolerancia a la conducción bajo sus efectos.',
                'alcance' => 'Conductores, contratistas y funcionarios que se trasladen en misión de la empresa.',
                'recursos' => 'Tiempo, personal, alcoholímetro y tecnología',
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Llevar a cabo pruebas periódicas de alcoholimetría',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 6 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Estrategias para identificar posibles casos de conducción bajo el efecto del alcohol y sustancias psicoactivas',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 6 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Procedimiento en caso de presentarse conducción bajo el influjo de alcohol o sustancias psicoactivas',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 1 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Mecanismos de comunicación y campañas de prevención vial',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 1 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Campaña de prevención del consumo de alcohol y sustancias psicoactivas',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 1 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Socialización del Reglamento interno de trabajo y Código de Faltas y Sanciones',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 1 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Publicación de la política de no alcohol, tabaco y sustancias psicoactivas',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 1 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Publicación de hábitos de vida saludable',
                        'responsable' => 'SST',
                        'meses' => [],
                        'observaciones' => 'El modelo de CMK planea 10 al año.',
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Acuerdo del reconocimiento de las políticas por parte del trabajador',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Instructivo para realizar pruebas de alcohol',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'cobertura',
                        'nombre' => 'Cobertura',
                        'numerador' => 'Funcionarios cubiertos',
                        'denominador' => 'Total de funcionarios expuestos',
                        'meta' => 100,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'impacto',
                        'nombre' => 'Casos positivos',
                        'numerador' => 'Casos positivos',
                        'denominador' => 'Pruebas realizadas',
                        'meta' => 1,
                        'sentido' => 'desc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                        'meta_texto' => 'El número de casos positivos no será mayor al 1 % de la población expuesta',
                    ],
                ],
            ],
            [
                'codigo' => 'PR-SST-15',
                'nombre' => 'Programa de gestión del cansancio y la fatiga',
                'categoria' => 'pesv',
                'objetivo' => 'Identificar los factores contributivos que favorecen el cansancio del personal, para desarrollar estrategias que prevengan la fatiga en la conducción.',
                'alcance' => 'todos los trabajadores que conducen vehículos automotores y no automotores en misión de la organización',
                'recursos' => 'Económicos, Técnicos, Humanos',
                'formato' => 'FT-LCH-FATIGA',
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer objetivos y metas',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer indicadores de gestión',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer los mecanismos para controlar el riesgo',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Procedimiento de prevención del cansancio y la fatiga',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Campaña riesgos de conducir fatigado o estresado',
                        'responsable' => 'SST',
                        'meses' => [3, 10],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Pausas activas.',
                        'responsable' => 'SST',
                        'meses' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Seguimiento diario a vehículos',
                        'responsable' => 'SST',
                        'meses' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Seguimiento al reporte de condiciones de salud',
                        'responsable' => 'SST',
                        'meses' => [3, 6, 9, 12],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación de buenos hábitos y restricciones al conducir',
                        'responsable' => 'SST',
                        'meses' => [4, 10],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Realizar lista de chequeo de fatiga y somnolencia',
                        'responsable' => 'SST',
                        'meses' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Gestión de la fatiga en la conducción',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a Indicadores',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a las acciones tomadas frente a los hallazgos',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Implementación de acciones correctivas y preventivas. / correctivos',
                        'responsable' => 'SST',
                        'meses' => [11],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'eficacia',
                        'nombre' => 'Eficacia',
                        'numerador' => 'Hallazgos cerrados',
                        'denominador' => 'Total de hallazgos',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'casos',
                        'nombre' => 'Casos de fatiga reportados',
                        'numerador' => 'Casos reportados por cansancio y fatiga',
                        'denominador' => 'Cuestionarios aplicados',
                        'meta' => 0,
                        'sentido' => 'desc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                ],
            ],
            [
                'codigo' => 'RE-SST-67',
                'nombre' => 'Programa de gestión de la velocidad',
                'categoria' => 'pesv',
                'objetivo' => 'Disminuir los siniestros viales por excesos de velocidad',
                'alcance' => 'todos los vehiculos de la organización',
                'recursos' => 'Económicos, Técnicos, Humanos',
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer objetivos y metas',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer indicadores de gestión',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer los mecanismos para controlar el riesgo',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Definir los mantenimientos a realizar',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Implementar una política de gestión de la velocidad',
                        'responsable' => 'SST',
                        'meses' => [2],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Procedimiento de seguimiento y control a infractores de transito',
                        'responsable' => 'SST',
                        'meses' => [3],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Procedimiento de monitoreo de vehiculos y Seguimiento satelital (ANEXO)',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Realizar seguimiento periodico a los límites de velocidad estipulado por la empresa y establecidas en el codigo nacional de transito',
                        'responsable' => 'SST',
                        'meses' => [4],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'dotar a los vehículos nuevos de innovaciones tecnológicas, como los sistemas inteligentes de adaptación de la velocidad y de frenado de emergencia',
                        'responsable' => 'SST',
                        'meses' => [5],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'establecer límites de velocidad adecuados a la función de cada tipo de vía',
                        'responsable' => 'SST',
                        'meses' => [6],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'sensibilizar a los conductores y personal de la organización sobre los peligros de circular a una velocidad excesiva o inadecuada.',
                        'responsable' => 'SST',
                        'meses' => [7],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'identificar los tramos de alta accidentalidad por excesos de velocidad en la ruta y planes de viaje realizados en la organización',
                        'responsable' => 'SST',
                        'meses' => [8],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Taller formativo: Velocidad segura: acciones preventivas y precavidas',
                        'responsable' => 'SST',
                        'meses' => [9],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Seguimiento diario a vehiculos',
                        'responsable' => 'SST',
                        'meses' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Tabla de sanciones por excesos de velocidad',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'procedimiento de seguimiento y control a infractores de transito (ANEXO)',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a Indicadores',
                        'responsable' => 'SST',
                        'meses' => [7],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a las acciones tomadas frente a los hallazgos',
                        'responsable' => 'SST',
                        'meses' => [7],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Implementación de acciones correctivas y preventivas. / correctivos',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'trimestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'eficacia',
                        'nombre' => 'Eficacia',
                        'numerador' => 'Hallazgos cerrados',
                        'denominador' => 'Total de hallazgos',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'trimestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'efectividad',
                        'nombre' => 'Efectividad',
                        'numerador' => 'Vehículos que incumplieron los límites de velocidad',
                        'denominador' => 'Total de vehículos monitoreados',
                        'meta' => null,
                        'sentido' => 'desc',
                        'frecuencia' => 'trimestral',
                        'automatico' => false,
                        'meta_texto' => 'Reducir un 15 % los siniestros viales generados por exceso de velocidad',
                    ],
                ],
            ],
            [
                'codigo' => 'PR-SST-16',
                'nombre' => 'Programa de prevención de la distracción',
                'categoria' => 'pesv',
                'objetivo' => null,
                'alcance' => 'todos los trabajadores que conducen vehículos automotores y no automotores en misión de la organización',
                'recursos' => 'Económicos, Técnicos, Humanos',
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer objetivos y metas',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer indicadores de gestión',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer los mecanismos para controlar el riesgo',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Establecer un procedimiento de horas de conducción de los operadores',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Identificación de las principales distracciones de los conductores',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitar al conductor en normatividad vial, tolerancia en la vía y planificación de viaje',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Informar a los conductores sobre puntos criticos y de especial atención',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en el uso de equipos bidireccionales',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Formación de operadores en la conducción de vías congestionadas y manejo defensivo',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Procedimiento en caso de evidenciar distracción durante la conducción.',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Campaña de prevención de la distracción durante la conducción',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a Indicadores',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a las acciones tomadas frente a los hallazgos',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Implementación de acciones correctivas y preventivas. / correctivos',
                        'responsable' => 'SST',
                        'meses' => [11],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'eficacia',
                        'nombre' => 'Eficacia',
                        'numerador' => 'Hallazgos cerrados',
                        'denominador' => 'Total de hallazgos',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                ],
            ],
            [
                'codigo' => 'PR-SST-17',
                'nombre' => 'Programa de protección de actores viales',
                'categoria' => 'pesv',
                'objetivo' => 'Prevenir accidentes laborales en desplazamientos de los trabajadores en misión de la empresa',
                'alcance' => 'todos los trabajadores que conducen vehículos automotores y no automotores en misión de la organización',
                'recursos' => 'Económicos, Técnicos, Humanos',
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer objetivos y metas',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer indicadores de gestión',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer los mecanismos para controlar el riesgo',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Definir los Actores viales',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Procedimiento con las directrices de seguridad vial para promover la protección de los actores viales vulnerables (peatones, pasajeros, ciclistas y motociclistas) de la organización en sus desplazamientos laborales y la generación de hábitos seguros y procedimiento en caso de evidenciar incumplimientos de las directrices',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en seguridad vial para motociclistas',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en seguridad vial para peatones',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en seguridad vial para vehículos',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Señalización y normas de transito',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Guía de protección a los ciclistas',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'campañas de prevención vial en entorno a la protección de actores vulnerables.',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a Indicadores',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a las acciones tomadas frente a los hallazgos',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Implementación de acciones correctivas y preventivas. / correctivos',
                        'responsable' => 'SST',
                        'meses' => [11],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'eficacia',
                        'nombre' => 'Eficacia',
                        'numerador' => 'Hallazgos cerrados',
                        'denominador' => 'Total de hallazgos',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                ],
            ],
            [
                'codigo' => 'PR-SST-03',
                'nombre' => 'Programa de gestión ambiental (residuos y consumos)',
                'categoria' => 'ambiental',
                'objetivo' => 'Lograr ecoeficiencia en las acciones institucionales de carácter administrativo y misional, y reducir los impactos negativos al ambiente.',
                'alcance' => 'Todas las sedes y procesos de la empresa.',
                'recursos' => 'Económicos, Técnicos, Humanos',
                'formato' => 'FT-INS-AMB',
                'actividades' => [
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Fortalecer el uso del correo electrónico y restringir el acceso a impresoras',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Construir la línea base de consumo de papel por área',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Campañas para la reducción del consumo de papel',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Diseñar y publicar el procedimiento de no impresión de documentos innecesarios',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Campañas de uso eficiente de la energía',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Talleres de separación de residuos desde la fuente',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Inspecciones de cumplimiento de la guía de buenas prácticas de separación de residuos',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Diagnóstico de las sedes que entregan residuos aprovechables a recicladores',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Entrega de residuos aprovechables a recicladores de oficio',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Instalación de carteles de ahorro de agua en baños',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Publicaciones periódicas sobre ahorro de agua',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en residuos',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Capacitación en reciclaje y manejo de residuos',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a indicadores de consumo (papel, energía, agua) y residuos',
                        'responsable' => 'SST',
                        'meses' => [6, 12],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => null,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'papel',
                        'nombre' => 'Consumo de papel',
                        'numerador' => 'Resmas consumidas en el periodo',
                        'denominador' => 'Resmas del mismo periodo del año anterior',
                        'meta' => 95,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                        'meta_texto' => 'Disminuir 5 % el consumo anual de papel respecto al año anterior',
                    ],
                    [
                        'clave' => 'energia',
                        'nombre' => 'Consumo de energía',
                        'numerador' => 'Consumo de energía del periodo',
                        'denominador' => 'Consumo del mismo periodo del año anterior',
                        'meta' => 95,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                        'meta_texto' => 'Disminuir 5 % el consumo anual de energía respecto al año anterior',
                    ],
                    [
                        'clave' => 'agua',
                        'nombre' => 'Consumo de agua',
                        'numerador' => 'Consumo de agua del periodo',
                        'denominador' => 'Consumo del mismo periodo del año anterior',
                        'meta' => 95,
                        'sentido' => 'desc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                        'meta_texto' => 'Disminuir 5 % el consumo anual de agua respecto al año anterior',
                    ],
                    [
                        'clave' => 'separacion',
                        'nombre' => 'Separación en la fuente',
                        'numerador' => 'Residuos separados correctamente (kg)',
                        'denominador' => 'Residuos generados (kg)',
                        'meta' => 85,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                    [
                        'clave' => 'cobertura',
                        'nombre' => 'Cobertura de capacitación',
                        'numerador' => 'Trabajadores que participan',
                        'denominador' => 'Trabajadores programados',
                        'meta' => 100,
                        'sentido' => 'asc',
                        'frecuencia' => 'anual',
                        'automatico' => false,
                    ],
                ],
            ],
            [
                'codigo' => 'PR-SST-06',
                'nombre' => 'Programa de mantenimiento locativo, de máquinas, equipos y herramientas',
                'categoria' => 'sst',
                'objetivo' => 'Mantener en óptimas condiciones funcionales los equipos, herramientas e infraestructura de la organización.',
                'alcance' => 'Todas las áreas y equipos de la organización.',
                'recursos' => 'Económicos, Técnicos, Humanos, Infraestructura',
                // Los activos, su plan y los registros de lo realizado viven en
                // el módulo de Mantenimiento; aquí va el cronograma PHVA.
                'formato' => null,
                'actividades' => [
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer objetivos y metas',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer indicadores de gestión',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Establecer los mecanismos para controlar el riesgo',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'planear',
                        'nombre' => 'Definir los mantenimientos a realizar',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Mantenimiento locativo',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Control de vectores',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Lavado, limpieza y desinfección de los tanques de almacenamiento de agua',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Limpieza y mantenimiento preventivo de máquinas, equipos y herramientas',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Mantenimiento de grifería y aparatos sanitarios',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Mantenimiento de software',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Mantenimiento correctivo',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'hacer',
                        'nombre' => 'Revisión e inspección de mantenimiento',
                        'responsable' => 'SST',
                        'meses' => [],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a Indicadores',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'verificar',
                        'nombre' => 'Seguimiento a las acciones tomadas frente a los hallazgos',
                        'responsable' => 'SST',
                        'meses' => [7, 11],
                    ],
                    [
                        'fase' => 'actuar',
                        'nombre' => 'Implementación de acciones correctivas y preventivas',
                        'responsable' => 'SST',
                        'meses' => [1],
                    ],
                ],
                'indicadores' => [
                    [
                        'clave' => 'cumplimiento',
                        'nombre' => 'Cumplimiento',
                        'numerador' => 'Actividades ejecutadas',
                        'denominador' => 'Actividades programadas',
                        'meta' => 80,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => true,
                    ],
                    [
                        'clave' => 'eficacia',
                        'nombre' => 'Eficacia',
                        'numerador' => 'Hallazgos cerrados',
                        'denominador' => 'Total de hallazgos',
                        'meta' => 90,
                        'sentido' => 'asc',
                        'frecuencia' => 'semestral',
                        'automatico' => false,
                    ],
                ],
            ],
        ];
    }
}
